title: RocketMind
email: admin@rocketmind.co
baseurl: ""
url: "http://rocketmind.co"

markdown: kramdown
plugins:
  - jekyll-coffeescript
  - bootstrap

sass:
  load_paths:
    - css
    - _lib
  style: compressed
