defaults: &defaults
  working_directory: ~/project
  docker:
    - image: starefossen/ruby-node:2-8

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Ruby dependencies
          command: bundle install
      - run:
          name: Build
          command: bundle exec jekyll build --verbose
      - run:
          name: Validate HTML
          command: bundle exec htmlproofer ./_site --check-html --disable-external

workflows:
  version: 2
  build:
    jobs:
      - test
