version: 2
jobs:
  build:
    docker:
      - image: starefossen/ruby-node:2-8
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Ruby dependencies
          command: bundle install
      - run:
          name: Build
          command: bundle exec jekyll build --verbose
  test:
    docker:
      - image: starefossen/ruby-node:2-8
    working_directory: ~/project
    steps:
      - run:
          name: Validate HTML
          command: bundle exec htmlproofer ./_site --check-html --disable-external
workflows:
  version: 2
  build:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
