version: 2
jobs:
  build:
    docker:
      - image: jekyll/builder
        environment:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - checkout
      - run: 
          name: Jekyll build
          command: bundle exec jekyll build
      - run: 
          name: Validate HTML
          command: bundle exec htmlproofer ./_site --allow-hash-href --check-favicon --check-html --disable-external
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/

