defaults: &defaults
  working_directory: ~/project
  docker:
    - image: starefossen/ruby-node:2-8

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Ruby dependencies
          command: bundle install
      - run:
          name: Build
          command: bundle exec jekyll build --verbose
      - run:
          name: Validate HTML
          command: bundle exec htmlproofer ./_site --check-html --disable-external
  build:
    <<: *defaults
    filters:
      branches:
        only: master
    steps:
      - checkout
      - run:
          name: Ruby dependencies
          command: bundle install
      - run:
          name: Build
          command: bundle exec jekyll build --verbose
      - run:
          name: Deploy
          command: scp -rvp -oStrictHostKeyChecking=no ./_site/* root@dev.rocketmind.co:/var/www/rock/html
