version: 2
jobs:
  build:
    docker:
      - image: starefossen/ruby-node:2-8
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Ruby dependencies
          command: bundle install
      - run:
          name: Node dependencies
          command: npm install -g html-proofer --unsafe-perm
      - run:
          name: Build
          command: bundle exec jekyll build --verbose
      - run:
          name: Validate HTML
          command: bundle exec htmlproofer ./_site --check-html --disable-external
          
