version: 2
jobs:
  build:
    docker:
      - image: jekyll/builder
    steps:
      - checkout
      - run: 
          name: Jekyll build
          command: jekyll build
      - run: 
          name: Validate HTML
          command: bundle exec htmlproofer ./_site --allow-hash-href --check-favicon --check-html --disable-external
